server:
  port: 8084
spring:
  data:
    mongodb:
      host: localhost
      port: 28017
      database: phyloviz-web-platform


  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: http://localhost:8082/realms/phyloviz-web-platform/protocol/openid-connect/token/introspect
          client-id: phyloviz-web-platform-client
          client-secret: pMSHvXI4MiinYpRoN9QHGMcR5uIswFjJ
        jwt:
          jwk-set-uri: http://localhost:8082/realms/phyloviz-web-platform/protocol/openid-connect/certs

logging:
  level:
    org:
      springframework:
        web:
          server:
            adapter:
              AbstractReactiveWebInitializer: DEBUG
        security:
          web: DEBUG
    web: DEBUG
