pwp:
  base-url: http://localhost:8083
  react-client-url: http://localhost:4200
  static-folder-path: C:\ISEL\6th semester\PFC\phyloviz-web-platform\src\backend\microservices\gateway\src\main\resources\static\
  debug: true
  security:
    logout-url: /api/logout
    oauth2:
      redirect-uri: "/api/login/oauth2/code/{registrationId}"

  microservices:
    administration:
      uri: http://localhost:8088
      routes:
        - method: POST
          path: /projects
        - method: GET
          path: /projects
        - method: GET
          path: /projects/{projectId}
        - method: DELETE
          path: /projects/{projectId}
        - method: PATCH
          path: /projects/{projectId}
        - method: POST
          path: /projects/{projectId}/datasets
        - method: GET
          path: /projects/{projectId}/datasets
        - method: GET
          path: /projects/{projectId}/datasets/{datasetId}
        - method: DELETE
          path: /projects/{projectId}/datasets/{datasetId}
        - method: PATCH
          path: /projects/{projectId}/datasets/{datasetId}
        - method: POST
          path: /projects/{projectId}/datasets/{datasetId}/isolateData
        - method: DELETE
          path: /projects/{projectId}/datasets/{datasetId}/distance-matrices/{distanceMatrixId}
        - method: PATCH
          path: /projects/{projectId}/datasets/{datasetId}/distance-matrices/{distanceMatrixId}
        - method: DELETE
          path: /projects/{projectId}/datasets/{datasetId}/trees/{treeId}
        - method: PATCH
          path: /projects/{projectId}/datasets/{datasetId}/trees/{treeId}
        - method: DELETE
          path: /projects/{projectId}/datasets/{datasetId}/tree-views/{treeViewId}
        - method: PATCH
          path: /projects/{projectId}/datasets/{datasetId}/tree-views/{treeViewId}
        - method: DELETE
          path: /projects/{projectId}/files/typing-data/{typingDataId}
        - method: PATCH
          path: /projects/{projectId}/files/typing-data/{typingDataId}
        - method: DELETE
          path: /projects/{projectId}/files/isolate-data/{isolateDataId}
        - method: PATCH
          path: /projects/{projectId}/files/isolate-data/{isolateDataId}

    compute:
      uri: http://localhost:8086
      routes:
        - method: POST
          path: /projects/{projectId}/workflows
        - method: GET
          path: /projects/{projectId}/workflows
        - method: GET
          path: /projects/{projectId}/workflows/{workflowId}

    visualization:
      uri: http://localhost:8085
      routes:
        - method: GET
          path: /projects/{projectId}/datasets/{datasetId}/trees/{treeId}
        - method: GET
          path: /projects/{projectId}/datasets/{datasetId}/tree-views/{treeViewId}
        - method: GET
          path: /projects/{projectId}/datasets/{datasetId}/distance-matrices/{distanceMatrixId}
        - method: GET
          path: /projects/{projectId}/files/isolate-data/{isolateDataId}
        - method: GET
          path: /projects/{projectId}/files/isolate-data/{isolateDataId}/rows
        - method: GET
          path: /projects/{projectId}/files/typing-data/{typingDataId}
        - method: GET
          path: /projects/{projectId}/files/typing-data/{typingDataId}/profiles

    file-transfer:
      uri: http://localhost:8089
      routes:
        - method: POST
          path: /projects/{projectId}/files/typing-data
        - method: GET
          path: /projects/{projectId}/files/typing-data/{typingDataId}/file
        - method: POST
          path: /projects/{projectId}/files/isolate-data
        - method: GET
          path: /projects/{projectId}/files/isolate-data/{isolateDataId}/file


server:
  port: 8083

spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: aC29^iCMUfSyk^xpi7e1AUvfu96kbV


  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/phyloviz-web-platform

        registration:
          phyloviz-web-platform-client:
            provider: keycloak
            client-id: phyloviz-web-platform-client
            client-secret: whCCD9r37qj8mx9H7R4mzIrSezYf3H7R
            redirect-uri: "{baseUrl}/${pwp.security.oauth2.redirect-uri}"

            scope:
              - openid
              - email
              - profile
logging:
  level:
    root: debug
