pwp:
  base-url: http://localhost:8083
  react-client-url: http://localhost:4200
  security:
    logout-url: /api/logout
    oauth2:
      redirect-uri: "/api/login/oauth2/code/{registrationId}"

server:
  port: 8083

spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: aC29^iCMUfSyk^xpi7e1AUvfu96kbV
  cloud:
    gateway:
      default-filters:
        - TokenRelay=

      routes:
        - id: administration
          uri: http://localhost:8088
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
        - id: home
          uri: ${pwp.react-client-url}
          predicates:
            - Path=/**


  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/phyloviz-web-platform

        registration:
          phyloviz-web-platform-client:
            provider: keycloak
            client-id: phyloviz-web-platform-client
            client-secret: pZW9kZ05jHjLiOlYYhBAa9CGk1uL7bob
            redirect-uri: "{baseUrl}/${pwp.security.oauth2.redirect-uri}"

            scope:
              - openid
              - email
              - profile
logging:
  level:
    root: debug
