server:
  port: 8089

spring:
  config:
    import: application-shared.yml
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

data-repositories:
  upload-typing-data-repository: S3
  download-typing-data-repository: S3
  upload-isolate-data-repository: S3
  download-isolate-data-repository: S3

logging:
  level:
    root: debug